### ISSUE TITLE
Issue with reboot from the stock OFW (black screen freeze)

### ISSUE THREAD

**Issue by JrRadiant** [Spacecraft-NX/firmware#14]
Found an issue:
the system does not reboot into Hekate when rebooting via Power Options - Reboot from the stock firmware, OFW. The LED on the chip flashes blue and then glows green permanently, but the system hangs with a black screen.

The only workaround is holding the power button for 10 seconds to fix it.

**Comment by balika011** [comment]
What kind of switch do you have?
What firmware version did you use?
How did you boot into ofw?

**Comment by JrRadiant** [comment]
The console is Erista, ipatched one.
Latest firmware version, 11.0.1.
And booting OFW via Hekate.

**Comment by balika011** [comment]
This is the same as #12
