### ISSUE TITLE
No device detected

### ISSUE THREAD

**Issue by chronoss09** [Spacecraft-NX/firmware#16]
i need a help, it's my first flash for SPACECRAFT-NX on SX Core and i get this error, the chip is green and connected to my PC but it's not detected by the flash.bat :(
![Capture](https://user-images.githubusercontent.com/17669980/106006888-ff175b80-60b5-11eb-84cb-c7db1506d113.PNG)

**Comment by chronoss09** [comment]
Try with another computer and W10 and it work, my first computer have W7, on W10 it work at the first time and the flash is done. The first boot took me 3 or 4 minute to boot on Atmosphere. Thanks a lot, it work a charme ;)

**Comment by thiagotmdev** [comment]
i am with same problem, i need help.
