### ISSUE TITLE
Auto rebooting to any payload makes battery drain

### ISSUE THREAD

**Issue by lichtlichtlicht** [Spacecraft-NX/firmware#19]
Auto rebooting after power off so when i turn on my switch its already drain

**Comment by rschwenck** [comment]
I'm facing the same issue. In my case, I'm using Hekate, so when I turn off the console I can see few seconds later that the console is Powered ON on Hekate menu.

**Comment by balika011** [comment]
That's horizon os's normal behavior. Has nothing to do with the mod.
