### ISSUE TITLE
Failed to read! 6

### ISSUE THREAD

**Issue by gataka85** [Spacecraft-NX/firmware#25]
Good day,

i am trying to flash SX Core and i am getting this :
Spacecraft-NX DFU found!
Flashing bootloader updater.........................................................................................................................................................................
Waiting for the updater to boot...
Failed to open! 2
Backing up the current bootloader.
.Failed to write! 6
Failed to read! 6
.Failed to write! 6
Failed to write! 6

(this is repiting many times)

Spacecraft-NX DFU not found!
!!!DONE!!!
Press any key to continue . . .

**Comment by balika011** [comment]
You have some malware on your computer that keeps the com ports open
