### ISSUE TITLE
Slow SD card is not detected

### ISSUE THREAD

**Issue by blawar** [Spacecraft-NX/firmware#26]
micro sd card: PNY 512 Pro Elite

Spacecraft always errors out with "NO SD" with this card.  This same SD card seems slow to initially respond in windows, however it did work on the previous modchip firmware, and it works with AMS on my unpatched erista console.  Perhaps the timeout values are too tight?

edit:  My 1TB sandisk extreme works fine on this mariko switch, its an issue between the PNY 512 Pro Elite and spacecraft.

**Comment by Southsystemic** [comment]
This has happened multiple times with 256gb ONN cards also, only some of them give problems. You can try to turn on the switch without the card and then immediately insert the sd. Sometimes it works.

**Comment by balika011** [comment]
Known fusee issue. Can't reproduce with my cards.
If somebody sends me a card that has that issue i'll fix it.
