### ISSUE TITLE
Advice on brick Oled consoles with SpaceCraft V1

### ISSUE THREAD

**Issue by shadow2560** [Spacecraft-NX/firmware#30]
Hi,

I want to have your advice on recent topic witch says that SpaceCraft V1 could damage Oled consoles, see the subject here:
https://gbatemp.net/threads/psa-tutorial-hwfly-chips-will-brick-your-oled-here-is-how-to-avoid-it.605763

And this Github project witch explain the possible problem:
https://github.com/Pheeeeenom/payloadchecker

I want to know if it's possible that it can damage or not the console, I know that V2 have some modifications for Oled but are they so criticals?

I think that your advice on this could be realy important so that's why I ask that here.

Thanks.

**Comment by balika011** [comment]
Yes. I said that many times before, but for some reason nobody cares.
