### ISSUE TITLE
Compatibility with lite console

### ISSUE THREAD

**Issue by achm3t** [Spacecraft-NX/firmware#38]
Hello! I’ve managed to install new OLED hwfly chip with qfn fpga to switch lite and it is doing glitch process very well showing oled’s “no sd” screen.  Entering to hekate ends with black screen. Think this happens because chip expects oled screen, not the lite one. With pheeenom’s 0.40 firmware flashed I even can run into hekate and create Emunand, but when I am trying to launch it, console goes to black screen after Atmosphere logo :( (btw OFW boot option from hekate also leads to black). So the question is - is it possible to make a firmware for oled hwfly chip that would be compatible with lite console? 
I am not a programmer at all, but I think that it is purely software issue. Speed improvements in recent 0.6.2 are great and it would be nice to have it on lite, even if there would be 4 additional points to solder :)

**Comment by achm3t** [comment]
Ok, will answer by myself. Problem with booting atmosphere on lite with installed oled chip solved by powering chip from another 3.3v source (not from usual capacitor near sd reader)

**Comment by kalaloluthfan** [comment]
same issue:( can u help?
