### ISSUE TITLE
Freeze while flashing the modchip, and it's dead now

### ISSUE THREAD

**Issue by sthetix** [Spacecraft-NX/firmware#4]
Hi, do you have any idea to revive the modchip? It flashes several times just fine, but at one point it freezes and the chip is dead now.  afaik, it is a STM32 MCU right? do you have any idea to flash or restore it ? it is not detected on windows now. Thx

**Comment by balika011** [comment]
Unplugging the chip while flashing bootloader will brick the chip.
You are not supposed to flash the bootloader over and over again at the first place, only update the firmware.
It's a GD32F350CBT6. You can revive it with a GD-Link.
