### ISSUE TITLE
Red led on chip after flash HWFly / emmc bricked?

### ISSUE THREAD

**Issue by MarcoInc** [Spacecraft-NX/firmware#46]
Hi everyone!
Many months ago I tried to flash a chip via USB in my Mariko to version 0.62 of HWFly, but without success since it went in boot / training loop for many hours. So I restored the original firmware and bootloader of my chip and used the console without problems for months, and I was waiting for new versions that could fix the problem.
Yesterday I wanted to try flashing my chip and with 0.70, of HWFly hoping for some fix, and bootloop / training again for a long time, and then I decided to turn off the console to be able to try to start the console again but one thing happened strange:
together with the usual green / yellow LED flashing for a quarter of a second the LED lights up red and then repeat the loop the green / yellow LEDs and repeat and repeat .... not paying attention to what I did a restore the original firmware and bootloader and at start-up, instead of turning on normally, after a few seconds of the classic blue LED, the LED turns solid red without flashing. I have made many attempts to flash and return to original firmware and bootloader ... nothing to do.
Could this be the problem with the EMMC? I make other attempts to find the problem.
I unplugged the chip from the original plug of the EMMC I put the original EMMC previously inserted in the mod chip and the console and black screen, as if the EMMC has fucked up great and which is why the led of the chip is glowed red.
How is it possible that the emmc was damaged through the hwfly firmware after the first boot of version 0.70?
Do you have solutions?
Although I am convinced that my switch is to be thrown away ..
ps. sorry my english but I am a foreigner :/
pps. returning to 0.70 of the hwfly, the problem remains

**Comment by DenverAttack** [comment]
Have sx lite, work fine on spacecraft 0.2.0 and 3.0-mod, but on hwfly-nx 0.7.0 and 0.7.1 stuck on loop training

**Comment by balika011** [comment]
hwfly isn't supported
