### ISSUE TITLE
??? WTF?

### ISSUE THREAD

**Issue by Konzolista** [Spacecraft-NX/firmware#47]
![1](https://user-images.githubusercontent.com/90899762/178163150-60a3aa45-f68f-4bbe-87e0-0c4425a5fe1e.jpg)
![2](https://user-images.githubusercontent.com/90899762/178163160-f9c4bd52-9360-4dfc-92fd-792be0a3900a.jpg)

**Comment by Pheeeeenom** [comment]
This has nothing to do with spacecraft.
