### ISSUE TITLE
fusee-primary as payload.bin results in a blackscreen

### ISSUE THREAD

**Issue by tuxuser** [Spacecraft-NX/firmware#6]
Unsure if its possibly an issue with Spacecraft-NX firmware or the problem is somewhere else, so feel free to close this issue if it's out-of-scope.

## Issue
fusee-primary is a no-show for me on spacecraft-nx.

(fusee-primary from AMS 0.16.2 is what I tried)

### Three options tried:

- `fusee-primary.bin as main payload.bin`, started directly by Spacecraft-NX
- `payload=fusee-primary.bin` in hekate
- `fss0=fusee-primary.bin` in hekate

### Symptoms when booting it directly as payload.bin:

- Chip glitches successfully (indicated by green - then off-LED)
- Screen stays black
- SD eject at this point produces screen output: `[NXBOOT] Couldn't parse boot0: I/O error!`

 Of course, the nature of I/O errror is obvious, when ejecting SD card while its being read from.

**UPDATE**:
Brand-new SDCard (128GB SanDisk), formatted FAT32, just Atmosphere on there + `fusee-primary.bin as payload.bin` yields:
`Failed to mount eMMC!`

Full thread on gbatemp.net: https://gbatemp.net/threads/spacecraft-nx-hekate-boots-atmospheres-fusee-primary-bin-gives-nxboot-failed-to-mount-emmc.579836

**Comment by balika011** [comment]
Wait for Atmosphere 0.17.x. 0.16.x has no modchip support.
