### ISSUE TITLE
Can't reflash SX firmware.

### ISSUE THREAD

**Issue by ludufre** [Spacecraft-NX/firmware#9]
I installed Spacecraft-NX to dump my partialseas.key on my Mariko with SX Core.

Now, I want to go back to SX firmware and the installer says:

![image](https://user-images.githubusercontent.com/4112077/103755904-5a8d8680-4fed-11eb-87d6-4949f5be0586.png)

It's not serial issue:
![image](https://user-images.githubusercontent.com/4112077/103755934-6711df00-4fed-11eb-88a3-04242a2ccd31.png)

**Comment by balika011** [comment]
Ask them

**Comment by ludufre** [comment]
No sir! Your firmware changed something. I've previously updated from 1.0 to 1.3 with same software. The problem started after flased your firmware. 

If you don't even want to bother to investigate. It would be fair to include this alert in README.md, because I am already in the second Mariko who does not accept to return to SX after installing your bootloader / firmware.

**Comment by ludufre** [comment]
@balika011 I solved. I run .\BootloaderUpdater.exe .\backup_2021_01_06_06_13_13.bin and now the Sx Updter recognizes.

This is worth adding to README.md. Can I provide a PR?

**Comment by balika011** [comment]
No, no sx support here.
